### ISSUE TITLE
setup Gitter

### ISSUE THREAD

**Issue by wizzup** [ppelleti/haskell-wiki-bugs#10]
Since you are already on github, you might want to setup [gitter](https://gitter.im) for this repo.

**Comment by ppelleti** [comment]
Can you elaborate on what Gitter is, and what value it will add to haskell-wiki-bugs?  I visited the website, but it wasn't immediately obvious to me what problem it's trying to solve.  Thanks!

**Comment by wizzup** [comment]
gitter is chat platform (like irc), you can create a room for each repo. others can logon using github account.

**Comment by ppelleti** [comment]
Thanks for the info!

Since the point of the haskell-wiki-bugs repo is to communicate with me, it seems like I would need to participate in gitter if we set it up.  I'm not really interested in having another platform that I need to participate in, and I'm not big on chat/instant messaging type things.  For me, the issue tracking in git works great.  And if we wanted to do chat, Haskell already has an IRC channel.  (Although I don't participate in it, since I'm not big on chat.)

That's at least how I feel now; you're welcome to try to convince me otherwise.  😃

**Comment by wizzup** [comment]
No problem, I do understand your decision. Thanks for doing this job.

Let me close this issue then.
